(source gnu)
(source melpa)

(depends-on "dockerfile-mode")
(depends-on "ethan-wspace")
(depends-on "flycheck")
(depends-on "go-mode")
(depends-on "js2-mode")
(depends-on "json-mode")
(depends-on "jsx-mode")
(depends-on "lua-mode")
(depends-on "puppet-mode")
(depends-on "nginx-mode")
(depends-on "terraform-mode")
(depends-on "web-mode")
(depends-on "yaml-mode")
